name: Validate API Key
description: A JS action to validate the API key format and write a message to a file.

inputs:
  api_key:
    description: The API key to validate.
    required: true

runs:
  using: node20
  main: index.js